### ISSUE TITLE
Could not load resource anymal_foot.dae and so on.

### ISSUE THREAD

**Issue by StanleyYake** [ANYbotics/anymal_b_simple_description#1]
Hello,There. I'm using ROS indigo and follow your guys tutorial, I type `roslaunch anymal_b_simple_description standalone.launch`but with following errors.
[ERROR] [1555640554.659628465]: Could not load resource [package://anymal_b_simple_description/meshes/anymal_foot.dae]: Collada: package://anymal_b_simple_description/meshes/anymal_foot.dae - Expected attribute "texcoord" at element "texture".
[ WARN] [1555640554.659845064]: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource package://anymal_b_simple_description/meshes/anymal_foot.dae in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /build/buildd/ogre-1.8-1.8.1+dfsg/OgreMain/src/OgreResourceGroupManager.cpp (line 756)
[ERROR] [1555640554.659962195]: Could not load model 'package://anymal_b_simple_description/meshes/anymal_foot.dae' for link 'LF_ADAPTER': OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource package://anymal_b_simple_description/meshes/anymal_foot.dae in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /build/buildd/ogre-1.8-1.8.1+dfsg/OgreMain/src/OgreResourceGroupManager.cpp (line 756)

I check the file is in `anymal_b_simple_description/meshes/anymal_foot.dae`,but can't decode.If there is anything I have made mistake,I am very apprecite if you can tell me.Thanks

**Comment by lisler** [comment]
Hi @StanleyYake 
We tested our model with ROS Melodic, running on Ubuntu 18.04. It [seems](https://answers.ros.org/question/301802/cannot-spawn-dae-robot-in-indigo/) that our collada file is not compatible with your installation.
