### ISSUE TITLE
Robot mass

### ISSUE THREAD

**Issue by grassjelly** [ANYbotics/anymal_b_simple_description#4]
Hi,

Thanks for releasing this repository to the public. 

I’m planning to add inertial matrices and transmission for this URDF. Is there anywhere I can find the information about the mass for each part? Thank you!

**Comment by remod** [comment]
Hi @grassjelly 

The [URDF](https://github.com/ANYbotics/anymal_b_simple_description/blob/master/urdf/anymal.urdf) already contains masses and inertias, can you elaborate what additional information you need?

**Comment by grassjelly** [comment]
Thanks for replying and causing confusion. Missed that tag, my bad. Cheers!
